## ScamBuster- Stop Scams in Real time
James Riedel, Spring 2026



#### Abstract:    

In the digital age that we live in, scams and digital fraud are becoming more and more prevalent every single day. Whether it’s via social media, over the phone, email, or text, scams are everywhere and are constantly evolving. Because of this, individuals often lack awareness and education regarding these scams therefore falling victim to them, resulting in financial loss, hardship, and emotional distress. This paper goes in depth on the project management scope and outline of ScamBuster, an open-source, community operated scam prevention system and network to combat these digital crimes. This system allows scams to be reported, documented, and publicized in real time to avoid having to rely on publications and law enforcement which is often too slow for the ever changing scam environment. Based on various project management concepts from the course, the network focuses on community engagement, workflow development, roadmaps, and more to accurately, urgently, and efficiently educate and update the community on digital scams.

#### Background:

In the society that we live in, technology and online services are apparent in most tasks in our everyday lives. While these services seem to make our lives more efficient and convenient, it comes with a cost; the risk of being scammed and taken advantage of. Every single online service opens their users up with this risk whether it is a simple social media site, or a banking application. Scammers usually either prey on vulnerable individuals using a fake persona or pretending to be a legitimate business, and then convince the individuals to send them money using various methods such as: crypto atm deposits, gift cards, wire transfers, Paypal/Venmo/Cashapp, and in some extreme circumstances, physical in person money mules. While anyone can fall victim to scams, the primary target for them are the elderly due to often lack of technological proficiency. (FBI, 2026)
Every single day, vulnerable individuals fall victim to these scams, often losing thousands, if not their entire life savings causing extreme distress and financial hardship. Lives get ruined daily over this. This happens due to many factors. First, with the constant enhancements of technology, such as AI, users have trouble staying proficient with it therefore are more prone to not be able to distinguish what to believe. In addition, there are very few sources for scam information and typically when there is, it is from a major publication site to where the scammer would have already been made aware of the exposure and most-likely already changed the scam so it is too late. Lastly, most scams originate outside of the United States therefore law enforcement don’t typically get involved or attempt to prevent and stop these scams which makes them much more common. This is a major problem which can be very mitigated and prevented with education and awareness.

#### Project Overview:

ScamBuster is a free, open source system and network that aims to help prevent and mitigate scams using direct community involvement and engagement. Users report their scam experience providing as much information and evidence as they can. It will then be uploaded and sent to a database where community members verify the legitimacy of the scam and if it is still active using various methods such as scambaiting (fake baiting the scammer to learn more information on the scam), call bots, and victim testimonials. Once verified, the report will then be flagged into a certain category based on factors such as risk level which users are able to view on the site. Users will additionally have the ability to mark notes into the report that they come across such as call recordings, scammer names, triggers to upset the scammers, etc. If the report is later flagged as inactive by someone, the scam report will return to an unverified status and require reverification to maintain legitimacy and remove scams that are no longer active. This way, users can stay informed of active scams, report new ones, and help make a safer community. In addition, there will be forums available to discuss various scam resources, insights, testimonials, etc. The network doesn’t aim to be associated with or mimic law enforcement; but more so to educate the public.

#### Project Scope/First Steps:

Early on, it may be difficult to implement a community driven network due to the lack of users to verify and act on various things. To combat this, the network will initially develop a bare-bones minimalistic version of the service that does an incredibly basic iteration of the main objective. This will be a simple site with 2 pages: the reporting form, and the reports page, both being very simplistic and bare. This is primarily in order to break the project into smaller tasks that can be added on later on. With this iteration, we can start establishing a community, as well as make sure that the things that are most important are being considered, which is giving the users access to the reports to be aware of them. Any form of verification is not established yet due to the lack of initial community where many reports would likely go unnoticed therefore remain unverified. Even if they could get verified, it would be from one person which would question the credibility of the site. Also forums and user interaction is intentionally not implemented yet also due to the lack of community.

#### Workflow:

In order to layout and organize the overall flow of the network, a workflow is needed. First, the user submits the scam which is available to do so on the home page. On the page, there will be many questions such as dates, times, type of scam, how the user came across it, any evidence, etc. At this point the user will get a confirmation email notifying them that they successfully reported a scam. The report then appears on the reports page, under the unverified tab. Users will be able to add any information they have on the specific scam as well as contribute legitimacy using the verify icon where the user can select if they discovered that the scam is still active or is shut down. One verification may not flag the report as verified; however if users have accurately verified many reports in the past, their verification is more impactful with the official status than other accounts as well as many verifications would result in the report being formally moved to the verified status. Once a report is verified, it is moved to the re-verification tab if someone marks it as no longer active which if more people flag it as such it will be removed. If the report is removed, it is moved to the legacy report tab where users can see all the past reports to make connections and potentially find patterns in scams and where they are coming from. This way, users are constantly up to date on various scams, are verified on legitimacy, and removed if outdated.

| ![](https://raw.githubusercontent.com/OREL-group/Project-Management/refs/heads/main/FINAL_PAPERS/riedel_jimmy_images/workflow.png) | 
| :--: |
| <b>Figure 1.</b> Caption test. [Store image as an issue](https://github.com/OREL-group/Project-Management/issues/279) or in the local directory. |

#### Roadmap:

Within the network, there are 4 phases in its lifecycle. The initial phase is the most bare-bones version of the network. It will be simply reporting a scam and users being able to see it. There will be no other user interaction beyond that in order to have some variation of a product. This will be for the initial 6 months of the project. 
The second phase implements verification and roles. Users will be able to verify reports as well as earn the verifier, reporter, and even potentially the moderator role. This is also where reporting and moderation comes into play. This will span over the next 6 months of the project as well to develop the verification and status algorithms. 
The third phase is where community engagement is large enough to develop forums to provide resources and engagement for the community. Users can share stories, guides, social media posts, spread awareness, etc. This is also where update logs, announcements, and transparent communication are. This will span over the next 3 years of the project, with minor feature enhancements and changes regarding user design and various feedback we would receive. 
The last phase is major expansion within the life of the project. There are many possibilities for this. A major one would be automation such as AI. Using automation can be used to verify scams by using AI to call or contact the source from the reports. This way scams can be updated even more in real time than before. AI can also be utilized to analyze patterns to potentially pinpoint the source of the scam more accurately. In addition, the network can be integrated into various platforms to automatically block scams. For example, if the scam is on Facebook messenger and an individual reports that account and the report is verified, the platform can automatically ban the account to prevent others from being scammed.

| ![](https://raw.githubusercontent.com/OREL-group/Project-Management/refs/heads/main/FINAL_PAPERS/riedel_jimmy_images/roadmap.png) | 
| :--: |
| <b>Figure 1.</b> Caption test. [Store image as an issue](https://github.com/OREL-group/Project-Management/issues/279) or in the local directory. |

#### Community Model:

The network is completely dependent on open community engagement and participation. There will be 4 roles users can earn, all based on merit such as accurate verifications, active engagement, positive behavior, etc. There will be various metrics that track these roles and they can be added or removed as well as users can have multiple roles. The first role is Learner. Learner is the most basic role and is automatically given to anyone who creates an account. Learners have access to make a report, view other reports, and verify them, however their influence to change statuses is very low, and would require many learners to change it. The next role is reporter. This is given when a user reports 5 different scams and are all verified. When they make a report, it gets moved more towards the top of reports and gets prioritized for verification. The third role is verifier. This is given when the user has accurately verified 5 different reports which all ended up being officially verified by user consensus. These users have a much higher influence in officially changing the statuses on unverified reports and need very few others to do so. The final role is moderator. This is given out on a case by case basis to individuals who show loyalty and merit and is chosen by the owner. Moderators have everything that the other roles have but also have the ability to moderate the forum, enforce rules, ban/mute someone, etc. They keep the network a safe and powerful resource.

#### Governance and Moderation:

Since the network is fully community based, it makes sense that all decisions are made public and influenced by the community as well. Full transparency is the main objective when it comes to governance in the network to allow the community to establish trust, confidence, and eagerness to participate. This is done by releasing frequent update logs, newsletters, and “town hall” meetings. 
In addition, like any public service, there are likely to be bots, spam, abuse, trolling, and even scams on the anti-scam site. To combat this, there needs to be a moderation system. Before moderation can be implemented, there needs to be a terms of service and code of conduct which states what would be allowed and not allowed while engaging with the site. In the site, there will be a report button next to every report and forum post. When pressed, the reporter will select what infraction the post violates and it will be submitted where moderators are notified and have access to it. Moderators then will determine if it does violate the guidelines to determine whether the post will be removed or not. In an instance of repeated offenses, accounts may be banned or even IP banned. This way all users can help keep the site safe which also encourages engagement and participation. This allows community moderation without giving users total control to maintain stability.

#### Technical Debt:

Technical debt is apparent in every project. In this particular instance, scams are forever changing and evolving. Because of this, there will be many things that would help the project accumulate technical debt over time. First, the specific platforms and ways users use the internet is also constantly changing therefore if the infrastructure and input options of the network is set up for one period of the internet, it may not allow the user to report things accurately later on due to lack of options or variety when reporting. For example, if current social media platforms are currently flooded with scams and the site is prepared for only those current scams to be displayed, if a newer social media came out that requires a whole different format to accurately report the scam, it may not allow the user to do so to the fullest potential resulting in scams going unreported. To combat this, the reporting format and overall layout of the reporting aspect needs to be incredibly versatile and universally formatted to accommodate every type of scam there is.
Another factor of technical debt is the project revolving around building a community rather than the stability of the site itself. The network can only function if the community exists and due to that it needs to constantly grow. As more users join and the site becomes more populated, some policies and algorithms may not be as beneficial and accurate as they used to be. For example, in early stages, one verifier may be able to change the status of a report but if that happens when there are hundreds of verifiers that exist, it can be abused very quickly to provide misinformation. To combat this, algorithms need to be percentage and majority based instead of set numbers.

#### Sustainability:

There are many factors that allow the network to sustain in the long term and continue to grow. First, the user base needs to constantly sign up more users as well as retaining existing users. In order to do this, there needs to be marketing or awareness of the network. This can be done using various methods, such as partnering with scam related organizations such as scambait Youtube channels or remote control software such as Anydesk (their software is often a tool used by scammers). Not only would this bring more users, it would also potentially bring revenue to the network. 
Revenue is also crucial to the survival and sustainability of the site. Without revenue, the servers, third party software, equipment and other costs cannot be paid. In addition to business partnerships, ads can be run on the site. The additional profit that is made can also be given to the users as an incentive to report scams therefore retaining the existing users. Donations can also be an option and can be elevated using scam awareness campaigns which bring in revenue but also spreads awareness and makes the site more well known.

#### Conclusion:

In conclusion, scams are always prevalent in society and are part of every online service. Victims constantly fall victim to scams and the effects can be catastrophic. ScamBuster allows scams to be identified and publicized in real time in order to educate the public before it’s too late and therefore protect the community making society an overall safer place. Its community driven infrastructure means that the network is created for the people, by the people so it is exactly what they want and benefits to the most potential. This open source project makes scam victims and those who are sick of scammers have a voice which they could never have before.

#### Work Cited:

Alicea, Bradley (2026). IS 340 Lecture Slides and Course Materials. University of Illinois Urbana-Champaign. 

Federal Bureau of Investigation. (n.d.). Common frauds and scams. U.S. Department of Justice. https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams 

Consumer Financial Protection Bureau. “Fraud and Scams.” Consumer Financial Protection Bureau, www.consumerfinance.gov/consumer-tools/fraud/. 

